# Generated by Django 4.1.4 on 2023-03-11 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('soyisim', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('image', models.FileField(blank=True, default='default.profil', upload_to='')),
                ('follow', models.ManyToManyField(related_name='takip', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ManyToManyField(related_name='takipci', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
