# Generated by Django 4.1.4 on 2023-03-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0002_userinfo_bgimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='isim',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='soyisim',
            new_name='surname',
        ),
    ]
