# Generated by Django 4.1.4 on 2023-03-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0003_rename_isim_userinfo_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='bgimage',
            field=models.FileField(blank=True, default='med2.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.FileField(blank=True, default='wallpaper1', upload_to=''),
        ),
    ]
