# Generated by Django 4.1.4 on 2023-03-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='count',
            field=models.IntegerField(null=True, verbose_name='begeni sayisi'),
        ),
    ]
