# Generated by Django 4.1.4 on 2023-03-07 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='user',
        ),
        migrations.AddField(
            model_name='likes',
            name='twit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appMy.tweet', verbose_name='twit'),
        ),
    ]
