# Generated by Django 4.1.4 on 2023-03-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0004_remove_likes_user_likes_twit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
