# Generated by Django 4.1.4 on 2023-03-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0005_delete_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(max_length=160, verbose_name='tweet'),
        ),
    ]
